display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      max-size: 8
      min-size: 2
      url: jdbc:mysql://cdb-dkzuspak.cd.tencentcdb.com:10031/car_db?useUnicode=true&characterEncoding=utf8
    password: bruce
    username: java.net
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: import.sql